@startuml uml_class
package com.upb.agripos.product {
  class Product {
    - String kode
    - String nama
    - String kategori
    - double harga
    - int stok
    + getKode(): String
    + setStok(int): void
  }

  interface ProductRepository {
    + save(Product): void
    + findByKode(String): Product
    + findAll(): List<Product>
    + deleteByKode(String): void
  }

  class JdbcProductRepository {
    + save(Product): void
    + findByKode(String): Product
  }
  JdbcProductRepository ..|> ProductRepository
}

package com.upb.agripos.payment {
  interface PaymentMethod {
    + pay(amount: double): PaymentResult
  }

  class CashPayment {
    + pay(amount: double): PaymentResult
  }
  class EWalletPayment {
    - String walletId
    + pay(amount: double): PaymentResult
    + setWalletId(String): void
  }
  class PaymentFactory {
    + getPaymentMethod(type:String): PaymentMethod
  }
  class PaymentService {
    - PaymentFactory factory
    + processPayment(type:String, amount:double): PaymentResult
  }

  class PaymentResult {
    + boolean success
    + String message
  }

  PaymentFactory --> PaymentMethod
  PaymentService --> PaymentFactory
  PaymentService --> PaymentResult
  CashPayment ..|> PaymentMethod
  EWalletPayment ..|> PaymentMethod
}

package com.upb.agripos.receipt {
  class ReceiptService {
    + generateReceipt(transaction): Receipt
  }
}

Product "1" -- "*" (order) Transaction : contains
@enduml
